version: "3.1"

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  #  mysql:
  #    image: mysql:5.7
  #    ports:
  #      - "3306:3306"
  #    command: --default-authentication-plugin=mysql_native_password
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_DATABASE: database

  s3:
    image: onedaycat/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: key
      MINIO_SECRET_KEY: "12345678"

volumes:
  esdata:
    driver: local
